import React, { useState } from 'react';
import { 
  FilePlus, Download, Loader2, AlertCircle, FileText, 
  MapPin, Calendar, Sprout, Building, CheckCircle2, Factory
} from 'lucide-react';
import { generateContent } from '../../services/gemini/client';
import { jsPDF } from 'jspdf';

export default function AiWhitePaperGenerator() {
  const [topic, setTopic] = useState("");
  const [crop, setCrop] = useState("");
  const [state, setState] = useState("");
  const [timePeriod, setTimePeriod] = useState("");
  
  const [generating, setGenerating] = useState(false);
  const [whitePaper, setWhitePaper] = useState(null);
  const [errorMsg, setErrorMsg] = useState("");

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!topic.trim() || !crop.trim() || !state.trim() || !timePeriod.trim()) {
      setErrorMsg("Please fill in all the required parameters.");
      return;
    }

    setGenerating(true);
    setErrorMsg("");
    setWhitePaper(null);

    const prompt = `Write a professional agricultural white paper on the topic: "${topic}".
    Context: Target Crop: ${crop}, Target State/Region: ${state}, Forecasting Period: ${timePeriod}.
    
    Structure your response as a valid JSON object. Return ONLY the raw JSON string. Do not include markdown tags.
    Keys required:
    1. "title": A formal title for the white paper.
    2. "executiveSummary": An overview paragraph.
    3. "marketAnalysis": 1-2 paragraphs on current market conditions.
    4. "researchFindings": Bullet points or a paragraph summarizing recent ag-science data.
    5. "governmentSchemes": Applicable policies or subsidies in ${state}.
    6. "industryTrends": Macro trends affecting this crop.
    7. "recommendations": Strategic recommendations for stakeholders.
    8. "conclusion": Final wrap-up.`;

    try {
      const response = await generateContent(prompt, {
        system_instruction: "You are a senior agricultural economist and policy analyst. Return only valid JSON.",
        temperature: 0.3
      });

      let cleanJson = response.trim().replace(/^```json\s*/i, "").replace(/```$/, "").trim();
      const parsed = JSON.parse(cleanJson);
      setWhitePaper(parsed);
    } catch (err) {
      console.error(err);
      setErrorMsg("Failed to generate white paper. Ensure your Gemini key is valid.");
    } finally {
      setGenerating(false);
    }
  };

  const handleDownloadPDF = () => {
    if (!whitePaper) return;
    const doc = new jsPDF();
    let y = 30;
    
    // Header
    doc.setFillColor(49, 87, 44);
    doc.rect(0, 0, 210, 15, "F");
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text("AgroIndia Policy & Research Institute", 15, 10);
    
    // Title
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    const titleLines = doc.splitTextToSize(whitePaper.title, 180);
    doc.text(titleLines, 15, y);
    y += titleLines.length * 7 + 5;
    
    // Metadata
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Focus: ${crop} | Region: ${state} | Scope: ${timePeriod}`, 15, y);
    y += 10;
    
    const writeSection = (title, content) => {
        if (!content) return;
        if(y > 260) { doc.addPage(); y = 20; }
        
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(49, 87, 44);
        doc.text(title, 15, y);
        y += 7;
        
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(40, 40, 40);
        const lines = doc.splitTextToSize(String(content), 180);
        
        lines.forEach(line => {
            if (y > 280) { doc.addPage(); y = 20; doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(40, 40, 40); }
            doc.text(line, 15, y);
            y += 5.5;
        });
        y += 8;
    };

    writeSection("Executive Summary", whitePaper.executiveSummary);
    writeSection("Market Analysis", whitePaper.marketAnalysis);
    writeSection("Research Findings", whitePaper.researchFindings);
    writeSection("Government Schemes & Policies", whitePaper.governmentSchemes);
    writeSection("Industry Trends", whitePaper.industryTrends);
    writeSection("Strategic Recommendations", whitePaper.recommendations);
    writeSection("Conclusion", whitePaper.conclusion);

    // Footer
    if(y > 275) { doc.addPage(); }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by AgroIndia AI White Paper Engine. For industry distribution.", 15, 290);

    const safeFilename = whitePaper.title.substring(0, 30).toLowerCase().replace(/[^a-z0-9]+/g, "_");
    doc.save(`${safeFilename}_whitepaper.pdf`);
  };

  return (
    <div className="space-y-6 animate-fadeIn antialiased">
      <div className="flex items-center gap-2.5 mb-6">
        <div className="p-2.5 bg-[#31572c]/10 rounded-xl">
          <FilePlus className="h-6 w-6 text-[#31572c]" />
        </div>
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-gray-900">AI White Paper Generator</h1>
          <p className="text-sm text-gray-500">Produce professional, structured agricultural white papers dynamically.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column: Form */}
        <div className="lg:col-span-4 space-y-6">
          <form onSubmit={handleGenerate} className="bg-white border border-gray-200 rounded-3xl p-6 shadow-sm space-y-5">
            <h3 className="text-xs font-bold text-gray-900 uppercase tracking-wider mb-2 flex items-center gap-2">
              <Building className="h-4 w-4 text-[#31572c]" /> Document Parameters
            </h3>
            
            <div>
              <label className="block text-xs font-bold text-gray-600 mb-1.5 uppercase">Research Topic</label>
              <textarea
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="e.g. Scaling organic nutrient management..."
                className="w-full h-24 p-3 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-[#31572c]/20 focus:border-[#31572c] outline-none resize-none"
                required
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-gray-600 mb-1.5 uppercase">Target Crop</label>
              <div className="relative">
                <input
                  type="text"
                  value={crop}
                  onChange={(e) => setCrop(e.target.value)}
                  placeholder="e.g. Basmati Rice"
                  className="w-full p-3 pl-9 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-[#31572c]/20 focus:border-[#31572c] outline-none"
                  required
                />
                <Sprout className="absolute left-3 top-3.5 h-4 w-4 text-gray-400" />
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold text-gray-600 mb-1.5 uppercase">Target State / Region</label>
              <div className="relative">
                <input
                  type="text"
                  value={state}
                  onChange={(e) => setState(e.target.value)}
                  placeholder="e.g. Punjab & Haryana"
                  className="w-full p-3 pl-9 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-[#31572c]/20 focus:border-[#31572c] outline-none"
                  required
                />
                <MapPin className="absolute left-3 top-3.5 h-4 w-4 text-gray-400" />
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold text-gray-600 mb-1.5 uppercase">Forecasting Period</label>
              <div className="relative">
                <input
                  type="text"
                  value={timePeriod}
                  onChange={(e) => setTimePeriod(e.target.value)}
                  placeholder="e.g. 2026 - 2030"
                  className="w-full p-3 pl-9 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-[#31572c]/20 focus:border-[#31572c] outline-none"
                  required
                />
                <Calendar className="absolute left-3 top-3.5 h-4 w-4 text-gray-400" />
              </div>
            </div>

            <button
              type="submit"
              disabled={generating}
              className="w-full bg-[#31572c] hover:bg-[#1a3018] text-white py-3.5 rounded-xl font-bold transition-all flex items-center justify-center gap-2 shadow-md disabled:opacity-60"
            >
              {generating ? <><Loader2 className="h-4 w-4 animate-spin" /> Synthesizing Paper...</> : <><FileText className="h-4 w-4" /> Generate White Paper</>}
            </button>
            
            {errorMsg && (
              <div className="p-4 bg-teal-50 text-teal-700 rounded-2xl flex gap-2 text-xs font-bold">
                <AlertCircle className="h-4 w-4 shrink-0" />
                <span>{errorMsg}</span>
              </div>
            )}
          </form>
        </div>

        {/* Right Column: Generated Paper */}
        <div className="lg:col-span-8">
          {!whitePaper && !generating ? (
            <div className="h-full min-h-[500px] flex flex-col items-center justify-center text-center p-8 bg-gray-50/50 border border-dashed border-gray-200 rounded-3xl">
              <Factory className="h-14 w-14 text-gray-300 mb-4" />
              <h3 className="text-sm font-bold text-gray-800">Awaiting Specifications</h3>
              <p className="text-xs text-gray-500 max-w-sm mt-2 leading-relaxed">
                Provide the industry topic, crop, location, and time period to dynamically generate a formatted, enterprise-grade white paper.
              </p>
            </div>
          ) : generating ? (
            <div className="h-full min-h-[500px] flex flex-col items-center justify-center text-center p-8 bg-white border border-gray-100 shadow-sm rounded-3xl">
              <Loader2 className="h-10 w-10 text-[#31572c] animate-spin mb-4" />
              <h3 className="text-sm font-bold text-[#31572c]">Drafting Industry White Paper...</h3>
              <p className="text-xs text-gray-400 mt-2">Correlating market trends, government policies, and scientific consensus.</p>
            </div>
          ) : (
            <div className="bg-white border border-gray-200 rounded-3xl p-8 shadow-sm flex flex-col h-full max-h-[800px]">
              
              <div className="flex items-start justify-between pb-6 border-b border-gray-100 mb-6 shrink-0">
                <div>
                  <h2 className="text-2xl font-black text-gray-900 leading-tight mb-2">{whitePaper.title}</h2>
                  <div className="flex gap-4 text-xs font-bold text-gray-500 uppercase tracking-wide">
                    <span className="flex items-center gap-1"><Sprout className="h-3 w-3 text-emerald-600"/> {crop}</span>
                    <span className="flex items-center gap-1"><MapPin className="h-3 w-3 text-emerald-600"/> {state}</span>
                    <span className="flex items-center gap-1"><Calendar className="h-3 w-3 text-emerald-600"/> {timePeriod}</span>
                  </div>
                </div>
                <button
                  onClick={handleDownloadPDF}
                  className="bg-[#31572c] text-white px-4 py-2.5 rounded-xl text-sm font-bold flex items-center gap-2 hover:bg-[#1a3018] transition-all shrink-0"
                >
                  <Download className="h-4 w-4" /> Export PDF
                </button>
              </div>
              
              <div className="overflow-y-auto pr-2 space-y-8 flex-1 pb-4">
                {[
                  { title: "Executive Summary", content: whitePaper.executiveSummary },
                  { title: "Market Analysis", content: whitePaper.marketAnalysis },
                  { title: "Research Findings", content: whitePaper.researchFindings },
                  { title: "Government Schemes & Policies", content: whitePaper.governmentSchemes },
                  { title: "Industry Trends", content: whitePaper.industryTrends },
                  { title: "Strategic Recommendations", content: whitePaper.recommendations },
                  { title: "Conclusion", content: whitePaper.conclusion }
                ].map((section, idx) => (
                  <div key={idx}>
                    <h3 className="text-sm font-bold text-[#31572c] uppercase tracking-wider mb-3 flex items-center gap-2">
                        <CheckCircle2 className="h-4 w-4 text-[#90a955]" /> {section.title}
                    </h3>
                    <div className="text-sm text-gray-700 leading-relaxed space-y-3">
                      {section.content.split('\n').map((paragraph, i) => (
                        <p key={i}>{paragraph}</p>
                      ))}
                    </div>
                  </div>
                ))}
              </div>

            </div>
          )}
        </div>
      </div>
    </div>
  );
}
